### ISSUE TITLE
Both ios and Android SDK zoho init fail

### ISSUE THREAD

**Issue by peterkuch** [zoho/SalesIQ-Mobilisten-iOS#25]
I don't know why now we can't init SDK 
-   Android
    implementation 'com.zoho.salesiq:mobilisten:4.2.8'
- IOS 
  pod 'Mobilisten', '4.2.8'
7 day ago not working also I contact to your support but they told me they checking and feedback to me but still not feedback.
![Screen Shot 2022-08-03 at 1 19 38 PM](https://user-images.githubusercontent.com/14107698/184586626-760431cc-2737-4fa5-8962-b64f74be2a4c.png)
![Screen Shot 2022-08-03 at 1 19 57 PM](https://user-images.githubusercontent.com/14107698/184586633-1a161f89-b2fd-4f87-82f7-14138ac6c49f.png)

![2022-08-03 13 14 11](https://user-images.githubusercontent.com/14107698/184586501-6329a161-183e-4438-993a-7513ca2f3799.jpg)
![Screen Shot 2022-08-15 at 1 19 08 PM](https://user-images.githubusercontent.com/14107698/184586536-7a58d7bc-4db6-4116-b6a7-8e5fdd4a5967.png)

**Comment by peterkuch** [comment]
I found my internet blocked your SDK. how can we avoid blocking SDK from the internet?

**Comment by DavidBhahirathan** [comment]
Hi @peterkuch,

Thank you for writing us. The initialization failed because the particular visitor is blocked in your portal. So please unblock and reopen your app. 

To unblock, from your SalesIQ web dashboard, please navigate to Settings > Block IP > remove IP and try again. 

For additional information, please refer to this [help guide](https://help.zoho.com/portal/en/kb/salesiq-2-0/for-associates/articles/blockip-2-0#Unblock__Manage_Blocked_IPs) for block/unblock IP.

If the issue persists, please feel free to mail us at (support@zohosalesiq.com)

Best regards,
Bhahirathan.

**Comment by peterkuch** [comment]
yes it's work thank
