### ISSUE TITLE
Does not work with Swift 5.1.2

### ISSUE THREAD

**Issue by AustinHunt** [zoho/SalesIQ-Mobilisten-iOS#4]
Attempted to follow your docs with a new project with both Swift and Objective-C and neither work. I get this error in Swift `Module compiled with Swift 5.0.1 cannot be imported by the swift 5.1.2 compiler.`

In Objective-C projects I don't even get an error, I merely have no api methods available.

**Comment by AustinHunt** [comment]
This is why the react-native project does not work as well. It looks like you have not compiled this framework for the latest iOS. See #3

**Comment by RishabhRaghunath** [comment]
Hi @AustinHunt 
Please find the SDK compiled using the Swift 5.1.2 compiler from the MobilistenBeta pod.
Since the framework is to be rebuilt for each swift version, we release quick support updates and bug fixes in the Beta repository.
Mobilisten Beta Repository: https://github.com/zoho/Mobilisten-iOS-Beta
